server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # about swagger
  servlet:
    multipart:
      enabled: true

cloud:
  aws:
    s3:
      bucket: image-bucket-hyeok
    credentials:
      access-key: AKIATJLYTU5KNUR3E66F
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  file:
    path: /home/ec2-user/
  level:
    org:
      hibernate:
        SQL: DEBUG

