server:
  port: 8080
spring:
  application:
    name: boardApplication-dev
  servlet:
    multipart:
      enabled: true
cloud:
  aws:
    s3:
      bucket: image-bucket-hyeok
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIATJLYTU5KNUR3E66F
      secret-key: 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

