server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # about swagger
  servlet:
    multipart:
      enabled: true

aws:
  bucket:
    name: image-bucket-hyeok
  accessKey: AKIATJLYTU5KNUR3E66F
  secretKey: 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
  region: ap-northeast-2

logging:
  file:
    path: /home/ec2-user/
  level:
    org:
      hibernate:
        SQL: DEBUG

